import express from "express";
import path from 'path';
const app=express();
const __dirname = path.resolve();
app.set("view engine","pug");
app.set("views",__dirname+"/src/views");
app.use("/public", express.static(__dirname + "/src/public"));
app.get("/",(req,res)=>res.render("home"));
const handleListen=()=>console.log(`Listening on http://localhost:3001`);
app.listen(3001,handleListen);